import Head from "next/head";
import React, { useEffect } from "react";
import Link from "next/link";
import LoginButton from "../components/login/LoginButton";
import { useUser } from "@auth0/nextjs-auth0/client";
import { useRouter } from "next/router";

//TODO: login screen + ask for name (or get from Auth0)
//TODO: form display ingredients correctly
//FIXME: when I add a new day, it overwrites the data

export default function Landing() {
  const { user, error: userError, isLoading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user) {
      //navigate to home
      router.push("/home");
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>MealMaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>MealMaster</h1>
        <p>Meal planning made easy</p>
      </div>

      <Link href={"/home"}>Start planning</Link>
      <LoginButton />
    </>
  );
}
